# Generated by Django 6.1 on 2026-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_criar_aluno_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_ultima_alteracao_contato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Maculino'), ('neutro', 'Neutro')], default='feminino', max_length=10),
            preserve_default=False,
        ),
    ]
