# Generated by Django 6.1 on 2026-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_data_ultima_alteracao_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dados_anonimizados',
            field=models.BooleanField(default=False),
        ),
    ]
