# Generated by Django 6.1 on 2026-09-26 01:27

import alunos.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_dados_anonimizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=alunos.fields.CampoCriptografado(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=alunos.fields.CampoCriptografado(max_length=400),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=alunos.fields.CampoCriptografado(max_length=100),
        ),
    ]
