# Generated by Django 6.1 on 2026-08-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario_horarios', '0001_initial'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='matriculas.matricula'),
        ),
        migrations.AddField(
            model_name='turma',
            name='Disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='calendario_horarios.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='calendario_horarios.professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='Sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='calendario_horarios.sala'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='calendario_horarios.turma'),
        ),
    ]
