"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv() # Puxa as variáveis do arquivo .env para a memória

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-key'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'autenticacao',
    'alunos',
    'matriculas',
    'notas',
    'financeiro',
    'calendario_horarios',
    'agenda',
    'documentos_certificados',
    'tarefas',
    'privacidade_lgpd',
    'recuperacao_senha',
]

AUTH_USER_MODEL = 'autenticacao.Usuario'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration


# MAILERS = {
#   "default": {
#      "BACKEND": "django.core.mail.backends.console.EmailBackend",
# },
#}


# Deixamos o PBKDF2 explícito aqui por ser a recomendação da OWASP contra ataques de força bruta.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",     # É o principal, que o Django vai usar pra encriptar (fazer o hash) das senhas novas.
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",     # Os próximos ficam apenas de "reserva" caso o sistema precise ler alguma senha antiga que tenha sido salva com outro padrão antes.
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Reduzimos a sessão para 30 minutos (renovando a cada ação) para garantir a segurança dos dados acadêmicos.
SESSION_COOKIE_AGE = 1800     # Em 30 minutos, possui 1800 segundos.
SESSION_SAVE_EVERY_REQUEST = True     # A cada requisição do usuário o tempo volta a contar do zero.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True     # Expira na hora se o usuário fechar o navegador (aba/janela).



# Configurações de envio de e-mail via SMTP do Google
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Suas credenciais do portal
EMAIL_HOST_USER = 'portalalunopi@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'Portal do Aluno PI <portalalunopi@gmail.com>'



# Configuração de Logs de Auditoria
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'auditoria_format': {
            'format': '{levelname} | {asctime} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'arquivo': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'auditoria.log',
            'formatter': 'auditoria_format',
        },
    },
    'loggers': {
        'recuperacao_senha': {
            'handlers': ['arquivo'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Tempo, em segundos, que o link de recuperação continua válido.
# 3600 segundos = 1 hora.
PASSWORD_RESET_TIMEOUT = 3600