# Generated by Django 6.1 on 2026-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chave_2fa',
            field=models.CharField(blank=True, help_text='chave secreta usada para gerar os códigos do autenticador', max_length=32, null=True),
        ),
    ]
