# Generated by Django 6.1 on 2026-09-20 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_atualizar_email_superusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_registrado', models.CharField(blank=True, max_length=20)),
                ('evento', models.CharField(default='login_sucesso', max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
