# Generated by Django 6.1 on 2026-09-19 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_atualizar_email_superusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login_falho', 'Falha na Senha'), ('bloqueio', 'Bloqueio por Tentativas'), ('totp_falho', 'Falha no Código 2FA')], max_length=50)),
                ('risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('critico', 'Crítico')], default='baixo', max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP de onde veio a tentativa', null=True)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes extras do evento', null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
