# Generated by Django 6.1 on 2026-09-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_logauditoria'),
        ('autenticacao', '0006_colaborador'),
    ]

    operations = [
    ]
