# Generated by Django 6.1 on 2026-09-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_merge_0005_logauditoria_0006_colaborador'),
        ('autenticacao', '0008_criar_colaborador_teste'),
    ]

    operations = [
    ]
