# Generated by Django 6.1 on 2026-09-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0004_aluno_dados_anonimizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(max_length=100)),
                ('aceito', models.BooleanField(default=True)),
                ('versao_termo', models.CharField(default='1.0', max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_revogacao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to='alunos.aluno')),
            ],
        ),
    ]
