# Generated by Django 6.1 on 2026-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'EAD'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='regime',
            field=models.CharField(choices=[('semestral', 'Semestral'), ('anual', 'Anual')], default='semestral', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo_letivo',
            field=models.CharField(default='2026.2', help_text='Ex: 2026.2', max_length=6),
            preserve_default=False,
        ),
    ]
